name: Repository Dispatch

on:
  push:
    branches: [main, develop, testing]

jobs:
  releaseDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Release Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ORT-FI-8184-DevOps-2022S1G4/devops
          event-type: ms-shipping-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.event.after }}", "repository": "${{ github.repository }}", "token": "${{ github.token }}", "branch": "${{ github.event.ref }}"}'
